name: Build Win

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        version: 12.2
    
    - name: Download OpenCL headers
      run: |
        curl -o main.zip https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/heads/main.zip
        Expand-Archive -Path main.zip -DestinationPath .

    - name: Make
      run: |
        make all

    - name: Check results
      shell: bash
      run: |
        ls -a
