name: Build Win

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
    
    - name: Make
      run: make all

    - name: Check results
      shell: bash
      run: |
        ls -a
